### ISSUE TITLE
Error when install RISCOF

### ISSUE THREAD

**Issue by DatNguyen97-VN** [stnolting/neorv32-riscof#248]
Hi admin,
i install RISCOF, run command in your terminal: `pip3 install git+https://github.com/riscv/riscof.git`
then get error as:
```
Collecting git+https://github.com/riscv/riscof.git
  Cloning https://github.com/riscv/riscof.git to /tmp/pip-req-build-fmui_hyy
  Running command git clone --filter=blob:none --quiet https://github.com/riscv/riscof.git /tmp/pip-req-build-fmui_hyy
  Resolved https://github.com/riscv/riscof.git to commit 108fa2d4e824b3e37fcff82e4fbbb7243127320b
  Preparing metadata (setup.py) ... done
Collecting GitPython==3.1.17 (from riscof==1.25.3)
  Using cached GitPython-3.1.17-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: click>=7.1.2 in /usr/local/lib/python3.8/dist-packages (from riscof==1.25.3) (8.1.3)
Requirement already satisfied: Jinja2>=2.10.1 in /root/.local/lib/python3.8/site-packages (from riscof==1.25.3) (3.1.2)
Requirement already satisfied: pytz>=2019.1 in /root/.local/lib/python3.8/site-packages (from riscof==1.25.3) (2023.3)
Collecting riscv-config>=3.2.0 (from riscof==1.25.3)
  Using cached riscv_config-3.17.1-py2.py3-none-any.whl.metadata (704 bytes)
Collecting riscv_isac>=0.7.2 (from riscof==1.25.3)
  Using cached riscv_isac-0.18.0-py2.py3-none-any.whl.metadata (872 bytes)
Requirement already satisfied: gitdb<5,>=4.0.1 in /root/.local/lib/python3.8/site-packages (from GitPython==3.1.17->riscof==1.25.3) (4.0.10)
Requirement already satisfied: MarkupSafe>=2.0 in /root/.local/lib/python3.8/site-packages (from Jinja2>=2.10.1->riscof==1.25.3) (2.1.3)
Collecting Cerberus>=1.3.1 (from riscv-config>=3.2.0->riscof==1.25.3)
  Using cached Cerberus-1.3.5-py3-none-any.whl.metadata (6.0 kB)
Collecting ruamel.yaml>=0.17.16 (from riscv-config>=3.2.0->riscof==1.25.3)
  Using cached ruamel.yaml-0.18.6-py3-none-any.whl.metadata (23 kB)
Collecting pyyaml==5.2 (from riscv-config>=3.2.0->riscof==1.25.3)
  Using cached PyYAML-5.2.tar.gz (265 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      /root/.local/lib/python3.8/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_0qp1pu2/pyyaml_4830af83a8eb45de84c035b6229de749/setup.py", line 292, in <module>
          setup(
        File "/root/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/root/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/root/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/root/.local/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/root/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/root/.local/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 312, in run
          self.find_sources()
        File "/root/.local/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 320, in find_sources
          mm.run()
        File "/root/.local/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 564, in run
          self.add_defaults()
        File "/root/.local/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 601, in add_defaults
          sdist.add_defaults(self)
        File "/root/.local/lib/python3.8/site-packages/setuptools/command/sdist.py", line 106, in add_defaults
          super().add_defaults()
        File "/root/.local/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 252, in add_defaults
          self._add_defaults_ext()
        File "/root/.local/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 337, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "/tmp/pip-install-_0qp1pu2/pyyaml_4830af83a8eb45de84c035b6229de749/setup.py", line 200, in get_source_files
          self.cython_sources(ext.sources, ext)
        File "/root/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Please help me to fix this issue.
thanks

**Comment by stnolting** [comment]
Hey there!

I had some similar issue when setting up RISCOF on my machine. It was just a dependency/system issue and this helped me out: https://stackoverflow.com/questions/35991403/pip-install-unroll-python-setup-py-egg-info-failed-with-error-code-1

**Comment by stnolting** [comment]
Problem solved? 😉

**Comment by DatNguyen97-VN** [comment]
i installed python 3.10 via pyenv, result in the riscof is installed successfully
thank you Admin.
